### ISSUE TITLE
Please add instructions on how to revert if this fails

### ISSUE THREAD

**Issue by jpSimkins** [Goldweavers/bose_qc35-ubuntu#2]
I tried this process and no luck on my end. I want to get back to the original state but since I deleted:
```
/var/lib/gdm3/.config/systemd/user/sockets.target.wants/pulseaudio.socket
```

I do not know how to recover this. The rest is pretty straight forward. I should have backed up that file.

**Comment by Goldweavers** [comment]
Hello !

You can rewrite it with the following content:
```
[Unit]
Description=Sound System

[Socket]
Priority=6
Backlog=5
ListenStream=%t/pulse/native

[Install]
WantedBy=sockets.target
```

**Comment by jpSimkins** [comment]
Thanks! 

For me it was to actually create a symlink:
```
ln -s /var/lib/gdm3/.config/systemd/user/sockets.target.wants/pulseaudio.socket /usr/lib/systemd/user/pulseaudio.socket
```

I forgot to update this ticket so I appreciate your response
