### ISSUE TITLE
Ubuntu Budgie 20.04 LTS

### ISSUE THREAD

**Issue by fkromer** [Goldweavers/bose_qc35-ubuntu#3]
On Ubuntu Budgie 20.04 LTS (lighdm, not gdm3 version) it seems like some of the steps are not required. Head over to https://discourse.ubuntubudgie.org/t/bose-quitecomfort-35-bluetooth-coupling-with-ubuntu-budgie-20-04-lts/3531 to learn more. Probably this is worth a note...

**Comment by Goldweavers** [comment]
Hello @fkromer,

Thanks for your feedback, I just commited changes :)
