### ISSUE TITLE
Is there a way to do one-time donation to you? (e.g., PayPal, buymeacoffee)

### ISSUE THREAD

**Issue by pcdro** [Goldweavers/bose_qc35-ubuntu#5]
Hello!

I gave up a few times to make my QC35 2 work in my Ubuntu. well, new year, a new try, and this repo helped me with it! 

I am very grateful and would like to give support beyond a 'Star', do you have a [buy me coffee](https://www.buymeacoffee.com/), GitHub Sponsor, PayPal, etc. that I could send a thank you for this work?

**Comment by Goldweavers** [comment]
Hello Pedro !

Thanks for your support. I'm happy that it helped you, I had also really bad times with this headphone :)

Here is my paypal.me/goldweavers if you still want to donate

**Comment by pcdro** [comment]
Thank you! Done! 👊🏽
